{% set version = '1.2.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nloptr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nloptr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nloptr/nloptr_{{ version }}.tar.gz
  sha256: 1f86e33ecde6c3b0d2098c47591a9cd0fa41fb973ebf5145859677492730df97

  patches:
    # - 0001-build-nlopt-verbosely.patch
    # - 0002-do-not-build-shared-nlopt.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat (>= 0.8.1), knitr, rmarkdown, inline (>= 0.3.14)
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('nloptr')"           # [not win]
    - "\"%R%\" -e \"library('nloptr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=nloptr
  license: LGPL-3
  summary: ' Solve optimization problems using an R interface to NLopt. NLopt is a  free/open-source
    library for nonlinear optimization, providing a common interface for a number of
    different free optimization routines available online as well as original implementations
    of various other algorithms. See <http://ab-initio.mit.edu/wiki/index.php/NLopt_Introduction>
    for more information on the available algorithms. During installation of nloptr
    on  Unix-based systems, the installer checks whether the NLopt library is installed
    on the system. If the NLopt library cannot be found, the code is compiled using
    the NLopt source included in the nloptr package.'

  license_family: LGPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: nloptr
# Type: Package
# Title: R Interface to NLopt
# Version: 1.2.1
# Date: 2018-10-02
# Author: Jelmer Ypma <uctpjyy@ucl.ac.uk>, with contributions by Hans W. Borchers <hwborchers@googlemail.com> and  Dirk Eddelbuettel <edd@debian.org>
# Maintainer: Jelmer Ypma <uctpjyy@ucl.ac.uk>
# Description:  Solve optimization problems using an R interface to NLopt. NLopt is a  free/open-source library for nonlinear optimization, providing a common interface for a number of different free optimization routines available online as well as original implementations of various other algorithms. See <http://ab-initio.mit.edu/wiki/index.php/NLopt_Introduction> for more information on the available algorithms. During installation of nloptr on  Unix-based systems, the installer checks whether the NLopt library is installed on the system. If the NLopt library cannot be found, the code is compiled using the NLopt source included in the nloptr package.
# License: LGPL-3
# Suggests: testthat (>= 0.8.1), knitr, rmarkdown, inline (>= 0.3.14)
# LazyLoad: yes
# NeedsCompilation: yes
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# Packaged: 2018-10-03 07:37:01 UTC; ripley
# Repository: CRAN
# Date/Publication: 2018-10-03 08:01:36 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
