travis:
  secure:
    BINSTAR_TOKEN: fJVpjmr0e5amaKuLIheNwW1/6daDfI9eyAQef10MWTmEaeBLYxhDvzMzZOdlTGHj3Ei6HLOH2SUTaxiLXpjVbyw1ZkNRolmPjzCIyVobA6oJlnnVS7zTPb/jXqbm+q3H3mMqzwWuesO0+LiKDzVBBV6/HDrzp9EO0XuhgN+XIBwr8FySGpo52FKSW1WLxJAtufAgTT5nGfJPw830rLnFpYttF9drbcCRZ2nj6Eg4mgmQKuG4ir9bJBU5P3LajiclwhKs8T7IVwLnUpnYW/fEtvAoBdnNE968N8sNTffucEGbrNKgP8e9L4Es8wQuix3xH7TJtCqNFCJD+sNxMl4Qkph5Jtumkqnh1Ob1bDvVclFvd+yzx2hVyBg5hg08hDtUmz4OOUJ7oxTEE7C9ea/Rb+jjNKFioO3PuQqY4530yNjTAozIm5jvMlRnuFoZim9O07NnZhRWpZx9RNuB7ArpHRs77e78uRsgneeSQIdWMv6Tll/trpkmpOeLs0VzbaKr2i2raZdneK6rr69faRcgOn+VP/8uAb2CBAa/FZ5n9YnUynRTnwkNc/sE5aCSCRSo+B0qVdMEdpW663CORNF6l6TWA3qc03iHDgz9PkeV2aNLnSeuCoeIzJ17IESpqJgmpZI5d8KxfF1ebxl5VXC9EkAErq7SwG6lTvrtdayL75o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
