travis:
  secure:
    BINSTAR_TOKEN: vgcm8DJ06yrZUfYDqt16179F/M8x63zvVHQScVvYDL4lHooOPlI+PmSdA35qfHvGTq7HaAEbBeOR+MPTHPgNjIuJFWJ0GkCcsop3gcB4H8XJgGRqrpvJyzMWaK5ne1nCRk2yWidfW/vvgV9/cRzhbT0Hzd6VX2EfrUMZMqvQji5NSagGpJFRnAcvvd9pj0PWWBHE5ltXpMcE/DBMWBBfXq8oFOQlG/zUiykYm+Cfgfj9Wy6EiCEXlX1eQnRyKsRPWeEVhrye0iTJr2dH6RIEAhIw9gFdvRvFlnXQmMTVotlU29cvQkbIw1HYNTQIai7mvopNIg0oKsIQ8jr4+RdJ5WAYOj2DEUPz2iNrnNVRdb8Ew5EXdS6YvKr7V2xbjnCmNopiSl2VHP1GN/i0HRch4q2Wraucnn+lGToU7z9hPlm5H6jE4rQzZWdz3f4SJNCHr7kvWKNhO8jaJTodySzM86nGjoZisdgX9Kh4t2ltf4h7Ts2ZW22qBysQ//B7JwaAZBZnNBdnhEfHVjDSlnqyv7S0hY0fdM+Rr0+T52nxBT4J/Vd0rOi3dP86IZxnopeD/Kh9fTsRg7zPAwVw+4qStw+UFPfwkEcDv0CiL+Al35OUmBOr/ptLuadjc2iH5Mk7pbCV6soSAyVojCfjHuWt+9/tqc/40im/u7LurOIFYlk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
